<?php

namespace Amtgard\ActiveRecordOrm\Query\Builder\Statement;

use Amtgard\ActiveRecordOrm\Query\Builder\Statement\Expression\Expression;
use Amtgard\ActiveRecordOrm\Query\Builder\Statement\Expression\GroupByExpression;
use Amtgard\ActiveRecordOrm\Query\Builder\Statement\Expression\LimitExpression;
use Amtgard\ActiveRecordOrm\Query\Builder\Statement\Expression\OrderByExpression;
use Amtgard\ActiveRecordOrm\Query\Builder\Statement\Expression\SelectExpression;
use Amtgard\ActiveRecordOrm\Query\Builder\Statement\Expression\WhereExpression;
use Amtgard\Traits\Builder\Builder;
use Amtgard\Traits\Builder\Getter;
use Amtgard\Traits\Builder\Setter;

// https://dev.mysql.com/doc/refman/8.4/en/select.html
class Select extends Statement
{
    use Builder;
    use Getter;
    use Setter;

    private SelectExpression $selectExpr;
    private WhereExpression $whereExpression;
    private GroupByExpression $groupBy;
    private OrderByExpression $orderBy;
    private LimitExpression $limit;

    public function buildSql(): string
    {
        return parent::buildSql(); // TODO: Change the autogenerated stub
    }
}