<?php

namespace Tests\Unit\RecordSet;

use Amtgard\ActiveRecordOrm\RecordSet\InMemoryRecordSet;
use Amtgard\ActiveRecordOrm\RecordSet\PdoRecordSet;
use Amtgard\PHPUnit\AmtgardTestCase;
use PDOStatement;
use Phake;
use Tests\Util\Constants;

class InMemoryRecordSetTest extends AmtgardTestCase
{
    private PDOStatement $mockStatement;

    private array $statementDef;
    private array $fetchDataArray;

    private PdoRecordSet $recordSet;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->statementDef = json_decode(Constants::$SELECT_INTEG_DEFINITION, true);
        $this->fetchDataArray = json_decode(Constants::$SELECT_INTEG_FETCH_DATA, true);

        $this->mockStatement = Phake::mock(PDOStatement::class);
        Phake::when($this->mockStatement)->columnCount()->thenReturn(count($this->statementDef));
        foreach ($this->statementDef as $key => $value) {
            Phake::when($this->mockStatement)->getColumnMeta($key)->thenReturn($value);
        }
        Phake::when($this->mockStatement)->rowCount()->thenReturn(1);
        Phake::when($this->mockStatement)->fetch()->thenReturn($this->fetchDataArray);
    }

    public function testBuildInMemoryRecordSet(): void
    {
        self::assertDoesNotThrow(function () {
            $recordSet = new InMemoryRecordSet(Constants::$PDO_RECORD_SET_JSON);
        });

        $recordSet = new InMemoryRecordSet(Constants::$PDO_RECORD_SET_JSON);
        $encoded = json_encode($recordSet, JSON_PRETTY_PRINT);
        self::assertEquals(Constants::$PDO_RECORD_SET_JSON, $encoded);
    }

    public function testIterateRecords(): void {
        $recordSet = new InMemoryRecordSet(Constants::$PDO_RECORD_SET_JSON);
        self::assertTrue($recordSet->next());
        self::assertEquals(1, $recordSet->size());
        self::assertTrue($recordSet->hasActiveRecord());
        self::assertNotNull($recordSet->getRecord());
        self::assertFalse($recordSet->next());
        self::assertFalse($recordSet->hasActiveRecord());
        self::assertNull($recordSet->getRecord());
    }

    public function testGetStringValue(): void {
        $recordSet = new InMemoryRecordSet(Constants::$PDO_RECORD_SET_JSON);
        
        // Position the record set at the first record
        $recordSet->next();
        
        // Test the __get() method by accessing the string_value field
        $stringValue = $recordSet->string_value;
        
        // Assert that the value matches what's expected from the JSON data
        self::assertEquals("2", $stringValue);
    }

    public function testHasField(): void {
        $recordSet = new InMemoryRecordSet(Constants::$PDO_RECORD_SET_JSON);
        
        // Position the record set at the first record
        $recordSet->next();
        
        // Test that hasField() returns true for existing fields
        self::assertTrue($recordSet->hasField('string_value'));
        self::assertTrue($recordSet->hasField('id'));
        self::assertTrue($recordSet->hasField('int_value'));
        
        // Test that hasField() returns false for non-existent fields
        self::assertFalse($recordSet->hasField('non_existent_field'));
        self::assertFalse($recordSet->hasField('missing_field'));
    }
}