<?php

namespace Tests\Unit;

use Amtgard\ActiveRecordOrm\RecordSet;
use Amtgard\PHPUnit\AmtgardTestCase;
use PDOStatement;
use Phake;
use PHPUnit\Framework\MockObject\Exception;
use Tests\util\Constants;

class RecordSetTest extends AmtgardTestCase
{
    private PDOStatement $mockStatement;

    private array $statementDef;
    private array $fetchDataArray;

    private RecordSet $recordSet;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->statementDef = json_decode(Constants::$SELECT_INTEG_DEFINITION, true);
        $this->fetchDataArray = json_decode(Constants::$SELECT_INTEG_FETCH_DATA, true);

        $this->mockStatement = Phake::mock(PDOStatement::class);
        Phake::when($this->mockStatement)->columnCount()->thenReturn(count($this->statementDef));
        foreach ($this->statementDef as $key => $value) {
            Phake::when($this->mockStatement)->getColumnMeta($key)->thenReturn($value);
        }
        Phake::when($this->mockStatement)->rowCount()->thenReturn(1);
        Phake::when($this->mockStatement)->fetch()->thenReturn($this->fetchDataArray);
    }

    public function testBuildRecordSetDoesNotThrow() {
        self::assertDoesNotThrow(function () {
            $rs = new RecordSet($this->mockStatement);
        });
    }

    public function testGetDefinitionMatches() {
        $recordSet = new RecordSet($this->mockStatement);
        self::assertDoesNotThrow(function () use ($recordSet) {
            self::assertEquals(count($this->statementDef), count($recordSet->getDefinition()));
        });
    }

    public function testGetPdoDefinition() {
        $recordSet = new RecordSet($this->mockStatement);
        self::assertDoesNotThrow(function () use ($recordSet) {
            self::assertEquals(count($this->statementDef), count($recordSet->getPdoDefinition()));
        });
    }

    public function testWhenNextIsCalledThenFetchIsCalled() {
        $recordSet = new RecordSet($this->mockStatement);
        $recordSet->next();
        Phake::verify($this->mockStatement)->fetch();
    }

    public function testWhenNextIsCalledThenDataIsPopulated() {
        $recordSet = new RecordSet($this->mockStatement);
        $recordSet->next();
        self::assertNotNull($recordSet->id);
    }

    public function testWhenNextNotCalledThenDataIsNotPopulated() {
        $recordSet = new RecordSet($this->mockStatement);
        self::assertNull($recordSet->getRecord());
        self::assertNull($recordSet->id);
    }

    public function testRecordSetSize(): void
    {
        $recordSet = new RecordSet($this->mockStatement);
        $this->assertEquals(1, $recordSet->size());
    }

    public function testHasActiveRecord(): void
    {
        $recordSet = new RecordSet($this->mockStatement);
        $this->assertFalse($recordSet->hasActiveRecord());
        $recordSet->next();
        $this->assertTrue($recordSet->hasActiveRecord());
    }

    public function testWhenFinalNextIsCalledThenReturnsFalse() {
        Phake::when($this->mockStatement)->fetch()
            ->thenReturn($this->fetchDataArray)
            ->thenReturn(false);
        $recordSet = new RecordSet($this->mockStatement);
        self::assertNotNull($recordSet->next());
        self::assertFalse($recordSet->next());
        self::assertFalse($recordSet->hasActiveRecord());
    }
}